Bug/searchbar autocomplete
annk15/MTGKeywordHelper pull request #51
Opened 2024-08-03 23:00 UTC by git-hub-oscar

## Bugfix searchbar/autosuggestion box

### Description
This pull fixes the bug where elements shift on some viewports when searching for only one card. I set a minimum height for the card container, and I put the searchbar in a seperate search container.

### Details
- Fix shifting elements when searching
- Put the searchbar in a seperate container for easier flex

### References

<br>

2024-08-03 23:10 UTC, git-hub-oscar commented
The merge issues should be fixed now

2024-08-04 04:05 UTC, annk15 requested changes
Good work! It does however look like one of the old lines for the scroll button has been committed so it should be reverted before merging this.

2024-08-04 04:05 UTC, annk15 commented on interface/templates/index.html
> +        <button onclick="topFunction()" id="myBtn" title="Go to top">Top</button>
```suggestion
        <button id="myBtn" title="Go to top">Top</button>
```

2024-08-04 04:36 UTC, annk15 approved these changes
Everything looks good now, I will merge!

2024-08-04 04:37 UTC, merged